apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        all:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "tamishk/coit-frontend-signed*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfwPeR0F+kZQZqgFSxFDSkbXigwW4
                j17N8VjplCufLShpljoP9wJOLfFm2UjYOEPqo+XKTrCO9JwlxpxLO6Zm+w==
                -----END PUBLIC KEY-----
