apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../coit-frontend

replicas:
- name: coit-frontend 
  count: 3

# images:
# - name: tamishk/coit-frontend
#   newName: tamishk/coit-frontend
#   newTag: v2

namespace: preview
